### ISSUE TITLE
Error when attempting to run test

### ISSUE THREAD

**Issue by hwilliams-bod** [EvgeniyBel/testsTaskBoden#2]
Hi Yuaheni,

Thanks for preparing this code.

When I try to execute the tests I get the message below. Can you help to get  them up and running?

Cheers,

Herb

$ npm run test:all

> testsTaskBoden@1.0.0 test:all C:\dev\candidates\EPAM\yauheni\testsTaskBoden
> protractor conf.js

[15:36:31] E/configParser - Error code: 105
[15:36:31] E/configParser - Error message: failed loading configuration file conf.js
[15:36:31] E/configParser - Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: C:\dev\candidates\EPAM\yauheni\testsTaskBoden\conf.js
require() of ES modules is not supported.
require() of C:\dev\candidates\EPAM\yauheni\testsTaskBoden\conf.js from C:\dev\candidates\EPAM\yauheni\testsTaskBoden\node_modules\protractor\built\configParser.js is an ES module file as it is a .js file whose nearest parent 
package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename conf.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from C:\dev\candidates\EPAM\yauheni\testsTaskBoden\package.json.

    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1031:13)
    at Module.load (internal/modules/cjs/loader.js:879:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Module.require (internal/modules/cjs/loader.js:903:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at ConfigParser.addFileConfig (C:\dev\candidates\EPAM\yauheni\testsTaskBoden\node_modules\protractor\built\configParser.js:135:26)
    at Object.initFn [as init] (C:\dev\candidates\EPAM\yauheni\testsTaskBoden\node_modules\protractor\built\launcher.js:93:22)
    at Object.<anonymous> (C:\dev\candidates\EPAM\yauheni\testsTaskBoden\node_modules\protractor\built\cli.js:227:10)
    at Module._compile (internal/modules/cjs/loader.js:1015:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1035:10)
npm ERR! code ELIFECYCLE
npm ERR! errno 105
npm ERR! testsTaskBoden@1.0.0 test:all: `protractor conf.js`
npm ERR! Exit status 105
npm ERR!
npm ERR! Failed at the testsTaskBoden@1.0.0 test:all script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\hwilliams\AppData\Roaming\npm-cache\_logs\2020-10-28T15_36_31_494Z-debug.log

**Comment by hwilliams-bod** [comment]
After removing "type": "module",  from package.json the tests run, but sometimes fail.
Failures:

1) Scenario: Log in, add an item to the basket and go through checkout process until you get to the payment stage # e2e\tests\basket.feature:9
   √ Given Go to applications https://www.boden.co.uk # e2e\stepDefinitions\mainPage.steps.js:5
   √ And Sing In # e2e\stepDefinitions\signInPage.steps.js:5
   √ And I accept cookies # e2e\stepDefinitions\mainPage.steps.js:29
   √ Given Go to Women menu item Dresses & Jumpsuits section # e2e\stepDefinitions\mainPage.steps.js:9
   √ And I add item to basket # e2e\stepDefinitions\storePage.steps.js:6
   × And I open basket # e2e\stepDefinitions\basket.steps.js:7
       WebDriverError: element click intercepted: Element <a href="/en-gb/checkout/shopping-bag.html#nav" title="..." class="button mini-basket-drawer-checkout">Checkout securely</a> is not clickable at point (1685, 874). Other element would receive the click: <div id="overlay" class="overlay is-visible" role="dialog" tabindex="-1" aria-labelledby="overlay">...</div>
         (Session info: chrome=86.0.4240.111)
         (Driver info: chromedriver=86.0.4240.22 (398b0743353ff36fb1b82468f63a3a93b4e2e89e-refs/branch-heads/4240@{#378}),platform=Windows NT 10.0.18363 x86_64)

**Comment by hwilliams-bod** [comment]
Did you get all the tests to pass?

**Comment by EvgeniyBel** [comment]
@hwilliams-bod 
I fixed it, this error was due to the specifics of protractor working in headless mode. I fixed everything, now there should be no falls.
Please update and run tests again.
